### ISSUE TITLE
FYI: [To] Implement MsgPack

### ISSUE THREAD

**Issue by PallHaraldsson** [russolsen/transit-julia#2]
"MessagePack is not implemented yet."

Why not?

https://github.com/kmsquire/MsgPack.jl

I just found your package/Transit (and had not heard about MsgPack either). Not sure if you thought you needed to implement MessagePack yourself. Easy[er] to add with that package (or maybe yours is redundant?).

**Comment by russolsen** [comment]
Hello,

Sorry, my comment was a bit unclear. Transit is a higher level data interchange format that has two variants, one built on top of JSON and a second built on top of MessagePack. When I wrote that MessagePack was not implemented yet, I meant that I hadn't done the work of implementing the Transit variant that sits on MessagePack. Certainly if/when I get around to doing Transit on MessagePack I won't implement MessagePack myself.

I appreciate your pointing this out nevertheless.

Russ
